/* USER CODE BEGIN Header */
/**
  * @file  input_scan.c
  * @brief Centralized input scan – PCA9555 managed path
  *
  *  Owns the PCA9555 driver instance and the g_pca9555_raw cache that
  *  Key_t structs reference via pointer.  Encoder direct-GPIO handling
  *  remains in encoder.c / fsdr_analog.c and is unchanged.
  */
/* USER CODE END Header */

#include "input_scan.h"
#include "pca9555.h"

/* I2C2 handle generated by CubeMX in main.c */
extern I2C_HandleTypeDef hi2c2;

/* ── PCA9555 driver instance (private) ──────────────────────────────────── */
static PCA9555_t s_pca;

/* ── Shared cache (extern-declared in input_scan.h) ─────────────────────── */
uint16_t g_pca9555_raw = 0xFFFFU;   /* all bits high = all keys released */

/* ════════════════════════════════════════════════════════════════════════════
 *  Input_Init
 * ════════════════════════════════════════════════════════════════════════════ */

void Input_Init(void)
{
  PCA9555_Init(&s_pca, &hi2c2, INPUT_PCA9555_ADDR);
  /* Pre-populate cache with initial state; stays 0xFFFF on I2C failure */
  if (s_pca.ok) {
    PCA9555_ReadInputs(&s_pca);
    g_pca9555_raw = s_pca.raw;
  }
}

/* ════════════════════════════════════════════════════════════════════════════
 *  Input_Scan  — call once per main loop before Key_Poll()
 * ════════════════════════════════════════════════════════════════════════════ */

void Input_Scan(void)
{
  if (PCA9555_ReadInputs(&s_pca) == HAL_OK) {
    g_pca9555_raw = s_pca.raw;
  }
  /* On I2C error: g_pca9555_raw keeps its previous value.
   * Keys will appear "held" only if they were already pressed — acceptable
   * failure mode for a transient bus glitch. */
}

/* ════════════════════════════════════════════════════════════════════════════
 *  Input_F4_IsPressed  — live read for blocking scan-abort loops
 * ════════════════════════════════════════════════════════════════════════════ */

bool Input_F4_IsPressed(void)
{
  PCA9555_ReadInputs(&s_pca);
  /* Active-low: bit = 0 means pressed */
  return !((s_pca.raw >> PCA_BIT_F4) & 1U);
}
