/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    csdr_app.h
  * @brief   CSDR Application Layer
  *
  *  File này chứa toàn bộ logic ứng dụng SDR.
  *  Không conflict với bất kỳ file nào CubeMX generate.
  *
  *  Cách dùng trong main.c (generated by CubeMX):
  *
  *  // USER CODE BEGIN Includes
  *  #include "csdr_app.h"
  *  // USER CODE END Includes
  *
  *  // USER CODE BEGIN 2
  *  CSDR_Init();
  *  // USER CODE END 2
  *
  *  // USER CODE BEGIN 3 (inside while(1))
  *  CSDR_Loop();
  *  // USER CODE END 3
  *
  *  Trong stm32h7xx_it.c – thêm vào SysTick_Handler:
  *  // USER CODE BEGIN SysTick_IRQn 1
  *  CSDR_SysTickCallback();
  *  // USER CODE END SysTick_IRQn 1
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __CSDR_APP_H
#define __CSDR_APP_H

/* LO offset: hardware QSD runs freq+LO_OFFSET, NCO corrects back to baseband.
 * DC spike (LO leakage) appears at +LO_OFFSET in spectrum → outside crop window. */
#define LO_OFFSET  18000U

#ifdef __cplusplus
extern "C" {
#endif

#include "stm32h7xx_hal.h"
#include <stdint.h>
#include <stdbool.h>

/* ── SDR State ───────────────────────────────────────────── */
typedef enum {
  MODE_AM = 0, MODE_FM, MODE_USB, MODE_LSB, MODE_CW, MODE_COUNT
} SDR_Mode_t;

typedef enum {
  STEP_1=1, STEP_10=10, STEP_100=100,
  STEP_1K=1000, STEP_10K=10000, STEP_100K=100000
} FreqStep_t;

typedef struct {
  uint32_t    freq_hz;
  SDR_Mode_t  mode;
  uint8_t     band_idx;
  uint8_t     volume;
  uint8_t     squelch;
  FreqStep_t  step;
  bool        mute;
  bool        agc_fast;
  bool        nb_on;
  bool        nr_on;
  int16_t     rit_hz;
  bool        tx_mode;
  bool        si5351_ok;
  bool        qse_on;
  uint8_t     att_db;
  bool        pwr_hold;
  uint32_t    bw_hz;           /*!< Snapped BW Hz (from mode table)  */
  int16_t     if_shift_hz;    /*!< IF shift Hz, applied via NCO      */
  bool        display_dirty;
  uint8_t     usb_mode;
  /* Calibration */
  int32_t     xtal_ppm;        /*!< XTAL correction ±200 ppm       */
  int16_t     iq_gain_tenth;   /*!< IQ gain balance ±200 = ±20.0%  */
  int16_t     iq_phase_tenth;  /*!< IQ phase balance ±200 = ±20.0° */
  int16_t     audio_cal_db;    /*!< Audio input level ±30 dB        */
} SDR_State_t;

extern SDR_State_t g_sdr;

/* ── Constants ───────────────────────────────────────────── */
#define CSDR_FREQ_MIN_HZ       100000UL
#define CSDR_FREQ_MAX_HZ     30000000UL
#define CSDR_FREQ_DEFAULT_HZ   7100000UL

#define CSDR_AUDIO_SAMPLE_RATE  48000UL
#define CSDR_AUDIO_BLOCK_SIZE     256U
#define CSDR_AUDIO_BUF_TOTAL   (CSDR_AUDIO_BLOCK_SIZE * 2U)

/* Pin defines (từ CSDR.ioc) */
#define LCD_CS_Pin          GPIO_PIN_4
#define LCD_CS_GPIO_Port    GPIOA
#define LCD_DC_Pin          GPIO_PIN_0
#define LCD_DC_GPIO_Port    GPIOB
#define LCD_RST_Pin         GPIO_PIN_1
#define LCD_RST_GPIO_Port   GPIOB
#define LCD_BL_Pin          GPIO_PIN_15
#define LCD_BL_GPIO_Port    GPIOB
#define FLASH_CS_Pin        GPIO_PIN_0
#define FLASH_CS_GPIO_Port  GPIOD
#define ATT_DAT_Pin         GPIO_PIN_8
#define ATT_DAT_GPIO_Port   GPIOD
#define ATT_CLK_Pin         GPIO_PIN_9
#define ATT_CLK_GPIO_Port   GPIOD
#define ATT_LATCH_Pin       GPIO_PIN_10
#define ATT_LATCH_GPIO_Port GPIOD
#define BPF_S0_Pin          GPIO_PIN_12
#define BPF_S0_GPIO_Port    GPIOD
#define BPF_S1_Pin          GPIO_PIN_13
#define BPF_S1_GPIO_Port    GPIOD
#define BPF_OE_Pin          GPIO_PIN_11
#define BPF_OE_GPIO_Port    GPIOD
#define LPF_A0_Pin          GPIO_PIN_8
#define LPF_A0_GPIO_Port    GPIOC
#define LPF_A1_Pin          GPIO_PIN_9
#define LPF_A1_GPIO_Port    GPIOC
#define LPF_A2_Pin          GPIO_PIN_8
#define LPF_A2_GPIO_Port    GPIOA
#define TR_SW_Pin           GPIO_PIN_14
#define TR_SW_GPIO_Port     GPIOD
#define CPU_PW_Pin          GPIO_PIN_12
#define CPU_PW_GPIO_Port    GPIOB
#define CPU_PW_HOLD_Pin     GPIO_PIN_13
#define CPU_PW_HOLD_GPIO_Port GPIOB
#define FAN_Pin             GPIO_PIN_6
#define FAN_GPIO_Port       GPIOC
#define ENC_SW_Pin          GPIO_PIN_2
#define ENC_SW_GPIO_Port    GPIOA
#define MENU_KEY_Pin        GPIO_PIN_7
#define MENU_KEY_GPIO_Port  GPIOE
#define BAND_KEY_Pin        GPIO_PIN_8
#define BAND_KEY_GPIO_Port  GPIOE
#define MODE_KEY_Pin        GPIO_PIN_9
#define MODE_KEY_GPIO_Port  GPIOE
#define F1_KEY_Pin          GPIO_PIN_10
#define F1_KEY_GPIO_Port    GPIOE
#define F2_KEY_Pin          GPIO_PIN_11
#define F2_KEY_GPIO_Port    GPIOE
#define F3_KEY_Pin          GPIO_PIN_12
#define F3_KEY_GPIO_Port    GPIOE
#define F4_KEY_Pin          GPIO_PIN_13
#define F4_KEY_GPIO_Port    GPIOE
#define PTT_Pin             GPIO_PIN_14
#define PTT_GPIO_Port       GPIOE
#define DAH_KEY_Pin         GPIO_PIN_15
#define DAH_KEY_GPIO_Port   GPIOE
#define DIT_KEY_Pin         GPIO_PIN_10
#define DIT_KEY_GPIO_Port   GPIOB
#define NTC_Pin             GPIO_PIN_0
#define NTC_GPIO_Port       GPIOC
#define ALC_Pin             GPIO_PIN_1
#define ALC_GPIO_Port       GPIOC
#define VOLTAGE_IN_Pin      GPIO_PIN_3
#define VOLTAGE_IN_GPIO_Port GPIOA
#define FLASH_SCK_Pin       GPIO_PIN_10
#define FLASH_SCK_GPIO_Port GPIOC
#define FLASH_MISO_Pin      GPIO_PIN_11
#define FLASH_MISO_GPIO_Port GPIOC
#define FLASH_MOSI_Pin      GPIO_PIN_12
#define FLASH_MOSI_GPIO_Port GPIOC

/* I2C addresses */
#define WM8731_I2C_ADDR     (0x1AU << 1U)
#define SI5351_I2C_ADDR     (0x60U << 1U)
#define SI5351_XTAL_HZ      25000000UL

/* LCD */
#define LCD_W  320U
#define LCD_H  240U

/* NTC / ADC */
#define ADC_VREF_MV       3300U
#define ADC_FULL_SCALE    65536U
#define VOLT_DIV_RATIO    4U
#define NTC_R_SERIES_OHM  10000U
#define NTC_R_25C_OHM     10000U
#define NTC_BETA          3950U
#define FAN_TEMP_START_C  40U
#define FAN_TEMP_FULL_C   65U
#define FAN_PWM_MIN       200U
#define FAN_PWM_MAX       999U
#define SWR_WARN_THRESH   200U
#define POWER_OFF_HOLD_MS 3000U

/* ── API ─────────────────────────────────────────────────── */

/**
 * @brief  Gọi 1 lần trong USER CODE BEGIN 2 của main.c
 *         Khởi tạo toàn bộ ứng dụng SDR.
 */
void CSDR_Init(void);

/* Audio buffer accessors for BSP modules */
int32_t *CSDR_GetTxBuf(void);
int32_t *CSDR_GetRxBuf(void);
void     CSDR_ClearDspFlags(void);

/**
 * @brief  Gọi trong while(1) – USER CODE BEGIN 3
 *         Xử lý encoder, phím, DSP, display, USB.
 */
void CSDR_Loop(void);

/**
 * @brief  Gọi trong SysTick_Handler – USER CODE BEGIN SysTick_IRQn 1
 */
void CSDR_SysTickCallback(void);

/**
 * @brief  CDC receive callback – gọi từ USB_DEVICE/App/usbd_cdc_if.c
 *         trong CDC_Receive_FS():
 *         CSDR_CDC_Receive(Buf, *Len);
 */
void CSDR_CDC_Receive(uint8_t *buf, uint32_t len);

#ifdef __cplusplus
}
#endif
#endif /* __CSDR_APP_H */
