/* USER CODE BEGIN Header */
/**
 * @file  lcd_panel_config.h
 * @brief Compile-time panel selection for the FMC 8080-mode LCD driver.
 *
 *  Hardware is configured via tools/hw_config.py (interactive) or
 *  tools/select_hw_profile.py (profile-name).  Both write
 *  BSP/Inc/hw_config_active.h which this file includes.
 *
 *  All resolution-dependent code derives LCD_W and LCD_H from this header —
 *  do not hard-code 480 or 320 elsewhere.
 *
 *  hw_config.py defines LCD_W and LCD_H directly (supports portrait and all
 *  orientation variants).  select_hw_profile.py does not; in that case the
 *  #ifndef guards below derive them from HW_LCD_PANEL.
 *
 *  ST7796 480x320  -- landscape, wide SDR UI with sidebars (default)
 *  ST7789 240x320  -- portrait, compact SDR UI, lower FMC bandwidth
 *
 *  Include order:
 *    lcd_panel_config.h  (this file, included by lcd_render.h and lcd_bus_fmc.h)
 *    lcd_render.h        (SWAP16, Font6x8, line-buffer helpers)
 *    lcd_bus_fmc.h       (LCD_PushWindow, LCD_SetWindow, etc.)
 *    sdr_ui.h            (zone geometry and UI API)
 */
/* USER CODE END Header */

#ifndef LCD_PANEL_CONFIG_H
#define LCD_PANEL_CONFIG_H

/* ── Active hardware configuration ──────────────────────────────────────────
 * Generated by tools/hw_config.py or tools/select_hw_profile.py.
 * Defines: HW_LCD_PANEL, HW_LCD_MADCTL, HW_FMC_*, HW_FMC_GPIO_SPEED,
 *          HW_DMA_CHUNK_ROWS, and (when generated by hw_config.py) LCD_W/LCD_H. */
#include "hw_config_active.h"

/* ── Panel identifiers ────────────────────────────────────────────────────── */
#define LCD_PANEL_ST7796  1   /*!< ST7796S 480x320, landscape FMC 8080  */
#define LCD_PANEL_ST7789  2   /*!< ST7789V 240x320, portrait  FMC 8080  */

/* ── Active panel selection ───────────────────────────────────────────────── */
#define LCD_PANEL  HW_LCD_PANEL

/* ── Derived resolution constants ────────────────────────────────────────────
 * hw_config.py writes LCD_W and LCD_H directly into hw_config_active.h so
 * that portrait and landscape variants of each chip resolve correctly.
 * The #ifndef guards below are the fallback path for select_hw_profile.py
 * generated headers that only set HW_LCD_PANEL.                              */
#ifndef LCD_W
#  if HW_LCD_PANEL == LCD_PANEL_ST7796
#    define LCD_W  480U   /*!< Landscape pixel columns */
#    define LCD_H  320U   /*!< Landscape pixel rows    */
#  elif HW_LCD_PANEL == LCD_PANEL_ST7789
#    define LCD_W  240U   /*!< Portrait pixel columns  */
#    define LCD_H  320U   /*!< Portrait pixel rows     */
#  else
#    error "hw_config_active.h: HW_LCD_PANEL must be 1 (ST7796) or 2 (ST7789)."
#  endif
#endif /* LCD_W */

#endif /* LCD_PANEL_CONFIG_H */
